### ISSUE TITLE
PHP 7.2: create_function() is deprecated

### ISSUE THREAD

**Issue by jangrewe** [Piwigo/Piwigo-download_by_size#8]
Hi, i'm not sure if this plugin is still supported, but i'm getting this notice:
`Function create_function() is deprecated in [...]/plugins/download_by_size/main.inc.php`

**Comment by gerkow** [comment]
//Line 110
// functions
  $filename = preg_replace_callback('#\$escape\((.*?)\)#', function ($m){ return str2url($m[1]); }, $filename);
  $filename = preg_replace_callback('#\$upper\((.*?)\)#', function ($m){ return strtoupper($m[1]);}, $filename);
  $filename = preg_replace_callback('#\$lower\((.*?)\)#', function ($m){ return strtolower($m[1]); }, $filename);
  $filename = preg_replace_callback('#\$strpad\((.*?),(.*?),(.*?)\)#', function($m){
 return str_pad($m[1],$m[2],$m[3],STR_PAD_LEFT);}, $filename);
